services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  auth:
    build:
      context: ./services/auth/
      dockerfile: Dockerfile.dev
    container_name: auth
    environment:
      - AUTH_PORT=${AUTH_PORT}
    volumes:
      - ./services/auth/:/app
      - /app/tmp/
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    command: air


networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
