services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh --quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  auth:
    build:
      context: ./services/auth/
      dockerfile: Dockerfile.dev
    container_name: auth
    environment:
      - AUTH_PORT=${AUTH_PORT}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - BCRYPT_COST=${BCRYPT_COST}
      - JWT_SECRET=${JWT_SECRET}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - S3_URI={S3_URI}
    volumes:
      - ./services/auth/:/app
      - /app/tmp/
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    command: air
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
