services:
  mongodb:
    image: mongo:7
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backup:
    image: bitnami/mongodb:7
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - mongodb
    environment:
      MONGODB_ROOT_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_HOST: ${MONGODB_HOST}
    volumes:
      - mongodb_backups:/backups
    entrypoint: >
      /bin/bash -c "
      while true; do
        TIMESTAMP=$(date +\"%Y%m%d_%H%M%S\");
        mongodump --host ${MONGODB_HOST} --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --out /backups/dump_$TIMESTAMP;
        sleep ${BACKUP_INTERVAL};
      done;
      "

volumes:
  mongodb_data:
    driver: local
  mongodb_backups:
    driver: local
