services:
  auth-service:
    image: auth-service:latest
    ports:
      - "50051:50051"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    networks:
      - umrah-net

networks:
  umrah-net:
    driver: overlay
